// src/lib/components/compliance/ReportModal.svelte
<script lang="ts">
	import { createEventDispatcher, getContext } from 'svelte';
	import { toast } from 'svelte-sonner';
	import Modal from '$lib/components/common/Modal.svelte';
	import type { Writable } from 'svelte/store';
	import type { i18n as i18nType } from 'i18next';

	const i18n = getContext<Writable<i18nType>>('i18n');
	const dispatch = createEventDispatcher();

	export let show = false;
	export let messageId: string = '';
	export let chatId: string = '';

	let loading = false;
	let category = '';
	let title = '';
	let description = '';
	let contactInfo = '';
	let screenshots: File[] = [];
	let isAnonymous = false;

	// 举报分类选项
	const categories = {
		'inappropriate': '不当内容',
		'technical': '技术问题',
		'copyright': '版权问题',
		'spam': '垃圾信息',
		'misinformation': '虚假信息',
		'other': '其他问题'
	};

	const categoriesEn = {
		'inappropriate': 'Inappropriate Content',
		'technical': 'Technical Issue',
		'copyright': 'Copyright Issue', 
		'spam': 'Spam',
		'misinformation': 'Misinformation',
		'other': 'Other Issue'
	};

	$: categoryOptions = $i18n.language.startsWith('zh') ? categories : categoriesEn;

	async function handleScreenshotUpload(event: Event) {
		const target = event.target as HTMLInputElement;
		const files = target.files;
		
		if (!files) return;
		
		// 限制最多3张截图
		if (screenshots.length + files.length > 3) {
			toast.error('最多只能上传3张截图');
			return;
		}
		
		// 验证文件大小和类型
		for (const file of Array.from(files)) {
			if (file.size > 5 * 1024 * 1024) {
				toast.error('图片大小不能超过5MB');
				return;
			}
			
			if (!file.type.startsWith('image/')) {
				toast.error('只能上传图片文件');
				return;
			}
		}
		
		screenshots = [...screenshots, ...Array.from(files)];
	}

	function removeScreenshot(index: number) {
		screenshots = screenshots.filter((_, i) => i !== index);
	}

	async function submitReport() {
		if (!category || !title) {
			toast.error('请填写必填项');
			return;
		}

		loading = true;

		try {
			// 上传截图
			const uploadedScreenshots = [];
			for (const file of screenshots) {
				const formData = new FormData();
				formData.append('file', file);

				const uploadResponse = await fetch('/api/v1/reports/upload-screenshot', {
					method: 'POST',
					headers: {
						'Authorization': `Bearer ${localStorage.getItem('token')}`
					},
					body: formData
				});

				if (uploadResponse.ok) {
					const result = await uploadResponse.json();
					uploadedScreenshots.push(result.filename);
				}
			}

			// 提交举报
			const endpoint = isAnonymous ? '/api/v1/reports/anonymous' : '/api/v1/reports';
			const headers: Record<string, string> = {
				'Content-Type': 'application/json'
			};
			
			if (!isAnonymous) {
				headers['Authorization'] = `Bearer ${localStorage.getItem('token')}`;
			}

			const response = await fetch(endpoint, {
				method: 'POST',
				headers,
				body: JSON.stringify({
					category,
					title,
					description: description || null,
					message_id: messageId || null,
					chat_id: chatId || null,
					contact_info: contactInfo || null,
					screenshot_files: uploadedScreenshots
				})
			});

			if (response.ok) {
				toast.success('举报提交成功');
				dispatch('success');
				closeModal();
			} else {
				const error = await response.json();
				toast.error(error.detail || '提交失败');
			}
		} catch (err) {
			toast.error('网络错误，请稍后再试');
		} finally {
			loading = false;
		}
	}

	function closeModal() {
		show = false;
		// 重置表单
		category = '';
		title = '';
		description = '';
		contactInfo = '';
		screenshots = [];
		isAnonymous = false;
	}
</script>

<Modal bind:show size="md">
	<div class="p-6">
		<div class="flex justify-between items-center mb-6">
			<h2 class="text-xl font-semibold text-gray-900 dark:text-white">
				{$i18n.language.startsWith('zh') ? '举报反馈' : 'Report Feedback'}
			</h2>
			<button 
				on:click={closeModal}
				class="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300"
			>
				<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
					<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/>
				</svg>
			</button>
		</div>

		<form on:submit|preventDefault={submitReport} class="space-y-4">
			<!-- 举报类型 -->
			<div>
				<label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
					{$i18n.language.startsWith('zh') ? '举报类型' : 'Report Category'} *
				</label>
				<select 
					bind:value={category}
					class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:text-white"
					required
				>
					<option value="">
						{$i18n.language.startsWith('zh') ? '请选择类型' : 'Select Category'}
					</option>
					{#each Object.entries(categoryOptions) as [key, label]}
						<option value={key}>{label}</option>
					{/each}
				</select>
			</div>

			<!-- 标题 -->
			<div>
				<label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
					{$i18n.language.startsWith('zh') ? '问题标题' : 'Title'} *
				</label>
				<input 
					bind:value={title}
					type="text"
					class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:text-white"
					placeholder={$i18n.language.startsWith('zh') ? '简要描述问题' : 'Brief description'}
					required
				/>
			</div>

			<!-- 详细描述 -->
			<div>
				<label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
					{$i18n.language.startsWith('zh') ? '详细描述' : 'Detailed Description'}
				</label>
				<textarea 
					bind:value={description}
					rows="4"
					class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:text-white resize-none"
					placeholder={$i18n.language.startsWith('zh') ? '请详细说明遇到的问题...' : 'Please describe the issue in detail...'}
				></textarea>
			</div>

			<!-- 联系方式 -->
			<div>
				<label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
					{$i18n.language.startsWith('zh') ? '联系方式' : 'Contact Info'}
					<span class="text-gray-500 text-xs ml-1">
						({$i18n.language.startsWith('zh') ? '可选' : 'Optional'})
					</span>
				</label>
				<input 
					bind:value={contactInfo}
					type="text"
					class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:text-white"
					placeholder={$i18n.language.startsWith('zh') ? '邮箱或手机号' : 'Email or phone number'}
				/>
			</div>

			<!-- 截图上传 -->
			<div>
				<label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
					{$i18n.language.startsWith('zh') ? '截图' : 'Screenshots'}
					<span class="text-gray-500 text-xs ml-1">
						({$i18n.language.startsWith('zh') ? '最多3张，每张不超过5MB' : 'Max 3 files, 5MB each'})
					</span>
				</label>
				<input 
					type="file"
					accept="image/*"
					multiple
					on:change={handleScreenshotUpload}
					class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:text-white"
				/>
				
				<!-- 预览已选择的截图 -->
				{#if screenshots.length > 0}
					<div class="mt-2 flex flex-wrap gap-2">
						{#each screenshots as screenshot, index}
							<div class="relative">
								<img 
									src={URL.createObjectURL(screenshot)} 
									alt="Screenshot preview"
									class="w-20 h-20 object-cover rounded border"
								/>
								<button
									type="button"
									on:click={() => removeScreenshot(index)}
									class="absolute -top-1 -right-1 bg-red-500 text-white rounded-full w-5 h-5 flex items-center justify-center text-xs"
								>
									×
								</button>
							</div>
						{/each}
					</div>
				{/if}
			</div>

			<!-- 匿名选项 -->
			<div class="flex items-center">
				<input 
					type="checkbox"
					id="anonymous"
					bind:checked={isAnonymous}
					class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
				/>
				<label for="anonymous" class="ml-2 text-sm text-gray-600 dark:text-gray-400">
					{$i18n.language.startsWith('zh') ? '匿名提交' : 'Submit anonymously'}
				</label>
			</div>

			<!-- 提交按钮 -->
			<div class="flex justify-end gap-3 mt-6">
				<button
					type="button"
					on:click={closeModal}
					class="px-4 py-2 text-gray-600 dark:text-gray-400 hover:text-gray-800 dark:hover:text-gray-200 border border-gray-300 dark:border-gray-600 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-700"
				>
					{$i18n.language.startsWith('zh') ? '取消' : 'Cancel'}
				</button>
				<button
					type="submit"
					disabled={loading || !category || !title}
					class="px-4 py-2 bg-blue-600 hover:bg-blue-700 disabled:bg-gray-400 text-white rounded-lg font-medium"
				>
					{loading ? 
						($i18n.language.startsWith('zh') ? '提交中...' : 'Submitting...') : 
						($i18n.language.startsWith('zh') ? '提交举报' : 'Submit Report')
					}
				</button>
			</div>
		</form>
	</div>
</Modal>

// web/components/chat/ReportModal.tsx
'use client'

import React, { useState, useRef } from 'react'
import { useTranslation } from 'react-i18next'

export interface ReportModalProps {
  contentId: string
  contentType: 'text' | 'image' | 'video' | 'audio'
  contentSnapshot?: any
  isOpen: boolean
  onClose: () => void
  onReportSubmitted: (reportId: string) => void
}

export interface ReportFormData {
  category: string
  reason: string
  attachments: File[]
}

const REPORT_CATEGORIES = [
  { key: 'inappropriate_content', label: 'report.categories.inappropriate' },
  { key: 'misinformation', label: 'report.categories.misinformation' },
  { key: 'technical_issue', label: 'report.categories.technical' },
  { key: 'spam', label: 'report.categories.spam' },
  { key: 'harassment', label: 'report.categories.harassment' },
  { key: 'other', label: 'report.categories.other' }
] as const

const ReportModal: React.FC<ReportModalProps> = ({
  contentId,
  contentType,
  contentSnapshot,
  isOpen,
  onClose,
  onReportSubmitted
}) => {
  const { t } = useTranslation()
  const [formData, setFormData] = useState<ReportFormData>({
    category: '',
    reason: '',
    attachments: []
  })
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const fileInputRef = useRef<HTMLInputElement>(null)

  const handleCategoryChange = (category: string) => {
    setFormData(prev => ({ ...prev, category }))
    setError(null)
  }

  const handleReasonChange = (reason: string) => {
    setFormData(prev => ({ ...prev, reason }))
    setError(null)
  }

  const handleFileSelect = (event: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(event.target.files || [])
    const validFiles = files.filter(file => {
      // Limit file size to 10MB and allow common image types and documents
      const maxSize = 10 * 1024 * 1024
      const allowedTypes = ['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'application/pdf', 'text/plain']
      return file.size <= maxSize && allowedTypes.includes(file.type)
    })

    if (validFiles.length !== files.length) {
      setError(t('report.errors.invalidFiles', 'Some files were not added due to size or type restrictions'))
    }

    setFormData(prev => ({
      ...prev,
      attachments: [...prev.attachments, ...validFiles].slice(0, 5) // Max 5 files
    }))
  }

  const removeAttachment = (index: number) => {
    setFormData(prev => ({
      ...prev,
      attachments: prev.attachments.filter((_, i) => i !== index)
    }))
  }

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault()
    
    if (!formData.category) {
      setError(t('report.errors.categoryRequired', 'Please select a report category'))
      return
    }

    if (!formData.reason.trim()) {
      setError(t('report.errors.reasonRequired', 'Please provide a reason for reporting'))
      return
    }

    setIsSubmitting(true)
    setError(null)

    try {
      const submitFormData = new FormData()
      submitFormData.append('content_id', contentId)
      submitFormData.append('content_type', contentType)
      submitFormData.append('report_category', formData.category)
      submitFormData.append('report_reason', formData.reason)
      
      if (contentSnapshot) {
        submitFormData.append('content_snapshot', JSON.stringify(contentSnapshot))
      }

      formData.attachments.forEach((file, index) => {
        submitFormData.append(`attachment_${index}`, file)
      })

      const response = await fetch('/api/reports/submit', {
        method: 'POST',
        body: submitFormData,
        credentials: 'include'
      })

      const result = await response.json()

      if (!response.ok) {
        throw new Error(result.error || t('report.errors.submitFailed', 'Failed to submit report'))
      }

      onReportSubmitted(result.report_id)
    } catch (err) {
      setError(err instanceof Error ? err.message : t('report.errors.submitFailed', 'Failed to submit report'))
    } finally {
      setIsSubmitting(false)
    }
  }

  const handleBackdropClick = (event: React.MouseEvent) => {
    if (event.target === event.currentTarget && !isSubmitting) {
      onClose()
    }
  }

  if (!isOpen) return null

  return (
    <div 
      className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50 p-4"
      onClick={handleBackdropClick}
    >
      <div className="bg-white dark:bg-gray-800 rounded-lg shadow-xl max-w-md w-full max-h-[90vh] overflow-y-auto">
        <div className="p-6">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">
              {t('report.modal.title', 'Report Content')}
            </h2>
            <button
              onClick={onClose}
              disabled={isSubmitting}
              className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 focus:outline-none"
              aria-label={t('common.close', 'Close')}
            >
              <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>

          <form onSubmit={handleSubmit} className="space-y-4">
            {/* Content Info */}
            <div className="text-sm text-gray-600 dark:text-gray-400 bg-gray-50 dark:bg-gray-700 p-3 rounded">
              <div className="flex items-center gap-2">
                <span className="font-medium">{t('report.modal.contentType')}:</span>
                <span className="capitalize">{contentType}</span>
              </div>
              <div className="mt-1 text-xs text-gray-500 dark:text-gray-400">
                {t('report.modal.contentId')}: {contentId.slice(0, 8)}...
              </div>
            </div>

            {/* Report Category */}
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                {t('report.modal.categoryLabel', 'Report Category')} *
              </label>
              <div className="space-y-2">
                {REPORT_CATEGORIES.map((category) => (
                  <label key={category.key} className="flex items-center">
                    <input
                      type="radio"
                      name="category"
                      value={category.key}
                      checked={formData.category === category.key}
                      onChange={(e) => handleCategoryChange(e.target.value)}
                      disabled={isSubmitting}
                      className="mr-2 text-red-600 focus:ring-red-500"
                    />
                    <span className="text-sm text-gray-700 dark:text-gray-300">
                      {t(category.label, category.key.replace('_', ' '))}
                    </span>
                  </label>
                ))}
              </div>
            </div>

            {/* Report Reason */}
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                {t('report.modal.reasonLabel', 'Reason for Report')} *
              </label>
              <textarea
                value={formData.reason}
                onChange={(e) => handleReasonChange(e.target.value)}
                disabled={isSubmitting}
                rows={4}
                maxLength={1000}
                placeholder={t('report.modal.reasonPlaceholder', 'Please describe why you are reporting this content...')}
                className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-red-500 focus:border-red-500 dark:bg-gray-700 dark:text-gray-100 resize-none"
              />
              <div className="mt-1 text-xs text-gray-500 dark:text-gray-400 text-right">
                {formData.reason.length}/1000
              </div>
            </div>

            {/* File Attachments */}
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                {t('report.modal.attachmentsLabel', 'Attachments (Optional)')}
              </label>
              <div className="space-y-2">
                <input
                  ref={fileInputRef}
                  type="file"
                  multiple
                  accept="image/*,.pdf,.txt"
                  onChange={handleFileSelect}
                  disabled={isSubmitting}
                  className="hidden"
                />
                <button
                  type="button"
                  onClick={() => fileInputRef.current?.click()}
                  disabled={isSubmitting || formData.attachments.length >= 5}
                  className="w-full px-3 py-2 border-2 border-dashed border-gray-300 dark:border-gray-600 rounded-md hover:border-gray-400 dark:hover:border-gray-500 focus:outline-none focus:ring-2 focus:ring-red-500 focus:border-red-500 text-sm text-gray-600 dark:text-gray-400 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  {t('report.modal.selectFiles', 'Select Files')} (max 5, 10MB each)
                </button>
                
                {formData.attachments.length > 0 && (
                  <div className="space-y-1">
                    {formData.attachments.map((file, index) => (
                      <div key={index} className="flex items-center justify-between bg-gray-50 dark:bg-gray-700 p-2 rounded">
                        <span className="text-sm text-gray-700 dark:text-gray-300 truncate flex-1">
                          {file.name} ({(file.size / 1024 / 1024).toFixed(2)} MB)
                        </span>
                        <button
                          type="button"
                          onClick={() => removeAttachment(index)}
                          disabled={isSubmitting}
                          className="ml-2 text-red-500 hover:text-red-700 dark:text-red-400 dark:hover:text-red-300"
                          aria-label={t('common.remove', 'Remove')}
                        >
                          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                          </svg>
                        </button>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </div>

            {/* Error Display */}
            {error && (
              <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-md p-3">
                <div className="flex">
                  <svg className="h-5 w-5 text-red-400 mr-2 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                  <span className="text-sm text-red-700 dark:text-red-300">{error}</span>
                </div>
              </div>
            )}

            {/* Submit Button */}
            <div className="flex gap-3 pt-4">
              <button
                type="button"
                onClick={onClose}
                disabled={isSubmitting}
                className="flex-1 px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 bg-gray-100 dark:bg-gray-700 hover:bg-gray-200 dark:hover:bg-gray-600 rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {t('common.cancel', 'Cancel')}
              </button>
              <button
                type="submit"
                disabled={isSubmitting || !formData.category || !formData.reason.trim()}
                className="flex-1 px-4 py-2 text-sm font-medium text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 rounded-md disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center"
              >
                {isSubmitting ? (
                  <>
                    <svg className="animate-spin -ml-1 mr-2 h-4 w-4 text-white" fill="none" viewBox="0 0 24 24">
                      <circle cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" className="opacity-25"></circle>
                      <path fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" className="opacity-75"></path>
                    </svg>
                    {t('report.modal.submitting', 'Submitting...')}
                  </>
                ) : (
                  t('report.modal.submit', 'Submit Report')
                )}
              </button>
            </div>
          </form>

          {/* Terms Notice */}
          <div className="mt-4 text-xs text-gray-500 dark:text-gray-400">
            {t('report.modal.termsNotice', 'By submitting this report, you agree that the information provided is accurate and you understand that false reports may result in account restrictions.')}
          </div>
        </div>
      </div>
    </div>
  )
}

export default ReportModal
